// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shhnbluomlzqhdhvlppq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoaG5ibHVvbWx6cWhkaHZscHBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2NjQwOTMsImV4cCI6MjA1MzI0MDA5M30.XdZyx7ws-ZIn23l-gKEp5y5Z6O-qq6JtwrpU1eDTpCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);